apiVersion: co2e.gocrane.io/v1alpha1
kind: CloudCarbonFootprint
metadata:
  name: azure-swedencentral
spec:
  provider: Manual
  region: swedencentral
  zone: europe-north-az01
  locality: EU/Sweden/Stockholm/AZ01
  pue: "1.12"
  emissionFactor: "0.045"
  computeConfig:
    - nodeSelector:
        matchLabels: {}
      minWattsPerCPU: "0.74"
      maxWattsPerCPU: "3.5"
      memoryWattsPerGB: "0.392"
  storageConfig:
    - storageClass: managed-premium
      wattsPerTB: "1.2"
  networkingConfig:
    - storageClass: golden
      wattsPerGB: "0.001"
